In [1]:
#Варіант 33 (3)
import numpy as np

# 1. Створіть одновимірний масив (вектор) з парними числами від 2 до 20 та виведіть його значення.
vector = np.arange(2, 21, 2)
print("1. Вектор з парними числами від 2 до 20:")
print(vector)

1. Вектор з парними числами від 2 до 20:
[ 2  4  6  8 10 12 14 16 18 20]


In [2]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими дійсними числами від 0 до 1 та виведіть його значення.
matrix = np.random.uniform(0, 1, size=(3, 3))
print("2. Матриця 3x3 з випадковими дійсними числами від 0 до 1:")
print(matrix)

2. Матриця 3x3 з випадковими дійсними числами від 0 до 1:
[[0.21704689 0.13386029 0.78474905]
 [0.35956794 0.7027101  0.68531267]
 [0.08970193 0.88164582 0.48773234]]


In [3]:
# 3. Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 20 та виведіть його значення.
matrix = np.random.randint(1, 21, size=(3, 3))
print("3. Матриця 3x3 з випадковими натуральними числами від 1 до 20:")
print(matrix)

3. Матриця 3x3 з випадковими натуральними числами від 1 до 20:
[[ 5 12 11]
 [16  8  2]
 [19 18 12]]


In [4]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть мінімальний елемент.
matrix = np.random.uniform(0, 1, size=(4, 4))
print("4. Мінімальний елемент в матриці 4x4 з випадковими дійсними числами від 0 до 1:")
print(np.min(matrix))

4. Мінімальний елемент в матриці 4x4 з випадковими дійсними числами від 0 до 1:
0.02237111311599005


In [5]:
# 5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від 1 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.
array1 = np.random.randint(1, 16, size=7)
array2 = np.random.randint(1, 16, size=7)
print("5. Поелементні операції на масивах:")
print("Додавання:", array1 + array2)
print("Віднімання:", array1 - array2)
print("Множення:", array1 * array2)

5. Поелементні операції на масивах:
Додавання: [16  7 23 19 29 16 18]
Віднімання: [14  5 -7  9  1  4  2]
Множення: [ 15   6 120  70 210  60  80]


In [6]:
# 6. Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 3 до 30 та знайдіть їх добуток.
matrix1 = np.random.randint(3, 31, size=(3, 3))
matrix2 = np.random.randint(3, 31, size=(3, 3))
print("6. Добуток двох матриць 3x3 з довільними цілими числами від 3 до 30:")
print(np.dot(matrix1, matrix2))

6. Добуток двох матриць 3x3 з довільними цілими числами від 3 до 30:
[[1140 1641 1404]
 [1050 1518 1266]
 [ 863 1164 1080]]


In [7]:
# 7. Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 7 та перемножте їх між собою.
matrix1 = np.random.randint(1, 8, size=(4, 2))
matrix2 = np.random.randint(1, 8, size=(2, 5))
print("7. Добуток двох матриць розміром 4x2 та 2x5:")
print(np.dot(matrix1, matrix2))

7. Добуток двох матриць розміром 4x2 та 2x5:
[[43 31 77 51 33]
 [33 24 57 36 27]
 [34 25 56 33 30]
 [38 27 72 51 26]]


In [8]:
# 8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 9, size=(2, 2))
print("8. Обернена матриця для 2x2 з випадковими цілими числами від 1 до 8:")
print(np.linalg.inv(matrix))

8. Обернена матриця для 2x2 з випадковими цілими числами від 1 до 8:
[[-0.25        0.5       ]
 [ 0.33333333 -0.33333333]]


In [9]:
# 9. Створіть матрицю розміром 2x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix = np.random.uniform(0, 1, size=(2, 3))
print("9. Транспонована матриця 2x3 з випадковими дійсними числами від 0 до 1:")
print(matrix.T)

9. Транспонована матриця 2x3 з випадковими дійсними числами від 0 до 1:
[[0.9662542  0.65410467]
 [0.67297213 0.909998  ]
 [0.11844281 0.92475833]]


In [10]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=(4, 1))
print("10. Добуток матриці 3x4 на вектор 4x1:")
print(np.dot(matrix, vector))

10. Добуток матриці 3x4 на вектор 4x1:
[[153]
 [124]
 [ 93]]


In [11]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор — випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
matrix = np.random.uniform(0, 1, size=(2, 3))
vector = np.random.randint(1, 11, size=(3, 1))
print("11. Добуток матриці 2x3 на вектор 3x1:")
print(np.dot(matrix, vector))

11. Добуток матриці 2x3 на вектор 3x1:
[[ 9.4316426]
 [11.782132 ]]


In [12]:
# 12. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("12. Сума двох матриць розміром 4x4 з випадковими цілими числами від 1 до 10:")
print(matrix1 + matrix2)

12. Сума двох матриць розміром 4x4 з випадковими цілими числами від 1 до 10:
[[ 6  5  9  6]
 [10 16 18 10]
 [13 16  3 18]
 [19 13 15  7]]


In [13]:
# 13. Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть їх добуток.
matrix1 = np.random.uniform(-1, 1, size=(4, 4))
matrix2 = np.random.uniform(-1, 1, size=(4, 4))
print("13. Добуток двох матриць 4x4 з випадковими дійсними числами в діапазоні від -1 до 1:")
print(np.dot(matrix1, matrix2))

13. Добуток двох матриць 4x4 з випадковими дійсними числами в діапазоні від -1 до 1:
[[ 0.10327822  0.47635637  0.27269224  0.37325031]
 [ 0.01702723 -0.14649391  0.02685837  0.55376656]
 [-0.24611368  0.11080217  0.24634145  0.05053078]
 [-0.84383025 -0.97931415  0.08498771 -0.13332302]]


In [14]:
# 14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму елементів матриці.
matrix = np.random.uniform(-1, 1, size=(3, 3))
print("14. Сума елементів матриці розміром 3x3 з випадковими дійсними числами в діапазоні від -1 до 1:")
print(np.sum(matrix))

14. Сума елементів матриці розміром 3x3 з випадковими дійсними числами в діапазоні від -1 до 1:
-3.46086566467916


In [15]:
# 15. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix = np.random.uniform(-0.5, 0.5, size=(5, 5))
print("15. Вектор-стовпчик, що містить суму елементів кожного рядка матриці 5x5 з випадковими дійсними числами в діапазоні від -0.5 до 0.5:")
print(np.sum(matrix, axis=1).reshape(-1, 1))

15. Вектор-стовпчик, що містить суму елементів кожного рядка матриці 5x5 з випадковими дійсними числами в діапазоні від -0.5 до 0.5:
[[-1.51368797]
 [ 0.48433923]
 [-1.05661539]
 [-0.22694954]
 [-0.60291327]]


In [16]:
# Висновок:
# На лабораторній роботі було розглянуто різні операції з матрицями та векторами у середовищі Python з використанням бібліотеки NumPy.
# Було створено та заповнено випадковими значеннями матриці різних розмірів, виконано операції додавання, множення, транспонування, обчислення оберненої матриці, пошук мінімальних елементів та сум рядків.
# Виконані завдання допомогли закріпити знання з роботи з багатовимірними масивами.





